<a href="https://colab.research.google.com/github/Prince-techh/ML_learning/blob/ML_algorithm/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('species',axis=1)

In [ ]:
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svc = SVC(gamma ='auto')

In [ ]:
model_svc.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svc.score(X_test,y_test)

1.0

In [ ]:
#Now lets use the grid search CV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svc),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},cv = 5, return_train_score = False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.01016135, 0.00608363, 0.00799532, 0.00586061, 0.01014481,
        0.00542269, 0.00402279, 0.00354643]),
 'std_fit_time': array([0.00085862, 0.002821  , 0.00502395, 0.00186272, 0.00139225,
        0.00136007, 0.0008165 , 0.00012618]),
 'mean_score_time': array([0.00851426, 0.00403914, 0.00448856, 0.0040803 , 0.00740886,
        0.00428734, 0.00290089, 0.0026885 ]),
 'std_score_time': array([7.63699162e-04, 1.45917011e-03, 2.07721115e-03, 1.18548082e-03,
        3.02948354e-03, 1.91379656e-03, 2.38421078e-04, 8.33945249e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
result = pd.DataFrame(classifier.cv_results_)

In [ ]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010161,0.000859,0.008514,0.000764,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.006084,0.002821,0.004039,0.001459,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.007995,0.005024,0.004489,0.002077,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005861,0.001863,0.004080,0.001185,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.010145,0.001392,0.007409,0.003029,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.005423,0.001360,0.004287,0.001914,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004023,0.000817,0.002901,0.000238,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003546,0.000126,0.002689,0.000083,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
model_knn = KNeighborsClassifier()

In [ ]:
from sklearn.model_selection import GridSearchCV

classifier2 = GridSearchCV(
    model_knn,
    {
        'n_neighbors': [3, 5, 7, 9, 11],
        'weights': ['uniform', 'distance']
    },
    cv=5,
    return_train_score=False
)

In [ ]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [ ]:
result2 = pd.DataFrame(classifier2.cv_results_)

In [ ]:
result2[['param_n_neighbors','param_weights','mean_test_score']]

   param_n_neighbors param_weights  mean_test_score
0                  3       uniform         0.966667
1                  3      distance         0.966667
2                  5       uniform         0.973333
3                  5      distance         0.966667
4                  7       uniform         0.980000
5                  7      distance         0.980000
6                  9       uniform         0.973333
7                  9      distance         0.973333
8                 11       uniform         0.980000
9                 11      distance         0.986667

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifierR = RandomizedSearchCV(model_svc, {
    "C":[1,10,20,30],
    "kernel":['rbf',"linear"],
},n_iter = 4,cv = 5 ,return_train_score = False)

In [ ]:
classifierR.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
resultR = pd.DataFrame(classifierR.cv_results_)
resultR

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005171,0.001694,0.003715,0.001065,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
1,0.004701,0.000982,0.003108,0.000084,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004179,0.000070,0.003020,0.000096,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
3,0.004178,0.000507,0.002961,0.000150,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [ ]:
resultR[["param_kernel","param_C","mean_test_score"]]

  param_kernel  param_C  mean_test_score
0       linear       20         0.966667
1          rbf        1         0.980000
2          rbf       30         0.960000
3       linear        1         0.980000